version: 2.1

orbs:
  kicadcd: mundodisco8/kicad-manufacturing-files@dev:20_01_13

workflows:
  createFabricationOutputsAndStore:
      jobs:
        - kicadcd/initialSetup:
            name: Initial Setup
        - kicadcd/pickAndPlacePositions:
            name: Get Pick And Place Positions # best practice is to name each orb job
            projectPath: PROJECT_PATH
            PCBFile: "Calavera.kicad_pcb"
            includeVirtualComponentsFlag: false
            artifactsPath: "artifacts/"
            requires:
              - Initial Setup

        - kicadcd/gerberFiles:
            name: Generate Gerber files
            projectPath: PROJECT_PATH
            PCBFile: "Calavera.kicad_pcb"
            configFile: "Kiplot_config.yaml"
            artifactsPath: "artifacts/"
            requires:
              - Initial Setup

        - kicadcd/createBillOfMaterials:
            name: Generate BoM files
            projectPath: PROJECT_PATH
            xmlNetlist: "Calavera.xml"
            # template located in the support folder
            bomTemplate: "../Support/BoM_Template.xlsx"
            configFile: "bom.ini"
            artifactsPath: "artifacts/"
            requires:
              - Initial Setup
